/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppLeadsIdRouteImport } from './routes/app.leads.$id'
import { Route as AppPropertiesIdRouteImport } from './routes/app.properties.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/leads'
    | '/app/login'
    | '/app/notifications'
    | '/app/properties'
    | '/app/reports'
    | '/app/'
    | '/app/leads/$id'
    | '/app/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/activity'
    | '/app/leads'
    | '/app/login'
    | '/app/notifications'
    | '/app/properties'
    | '/app/reports'
    | '/app'
    | '/app/leads/$id'
    | '/app/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/leads'
    | '/app/login'
    | '/app/notifications'
    | '/app/properties'
    | '/app/reports'
    | '/app/'
    | '/app/leads/$id'
    | '/app/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/$id': {
      id: '/app/leads/$id'
      path: '/$id'
      fullPath: '/app/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsIdRoute: typeof AppLeadsIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsIdRoute: AppLeadsIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
